/*
 * My ebay alerts API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

import { ApiClient } from "../ApiClient";
import { Account } from "./Account";

/**
 * The Alert model module.
 * @module model/Alert
 * @version v1
 */
export class Alert {
  /**
   * Constructs a new <code>Alert</code>.
   * @alias module:model/Alert
   * @class
   * @param searchTerm {String}
   * @param email {String}
   */
  constructor(searchTerm, email) {
    this.searchTerm = searchTerm;
    this.email = email;
  }

  /**
   * Constructs a <code>Alert</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Alert} obj Optional instance to populate.
   * @return {module:model/Alert} The populated <code>Alert</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Alert();
      if (data.hasOwnProperty("uuid"))
        obj.uuid = ApiClient.convertToType(data["uuid"], "String");
      if (data.hasOwnProperty("owner"))
        obj.owner = Account.constructFromObject(data["owner"]);
      if (data.hasOwnProperty("search_term"))
        obj.searchTerm = ApiClient.convertToType(data["search_term"], "String");
      if (data.hasOwnProperty("interval_time"))
        obj.intervalTime = ApiClient.convertToType(
          data["interval_time"],
          "String"
        );
      if (data.hasOwnProperty("email"))
        obj.email = ApiClient.convertToType(data["email"], "String");
    }
    return obj;
  }
}

/**
 * @member {String} uuid
 */
Alert.prototype.uuid = undefined;

/**
 * @member {module:model/Account} owner
 */
Alert.prototype.owner = undefined;

/**
 * @member {String} searchTerm
 */
Alert.prototype.searchTerm = undefined;

/**
 * Allowed values for the <code>intervalTime</code> property.
 * @enum {String}
 * @readonly
 */
Alert.IntervalTimeEnum = {
  /**
   * value: "2"
   * @const
   */
  _2: "2",

  /**
   * value: "10"
   * @const
   */
  _10: "10",

  /**
   * value: "30"
   * @const
   */
  _30: "30"
};

/**
 * @member {module:model/Alert.IntervalTimeEnum} intervalTime
 * @default '30'
 */
Alert.prototype.intervalTime = "30";

/**
 * @member {String} email
 */
Alert.prototype.email = undefined;
