/*
 * My ebay alerts API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

import { ApiClient } from "../ApiClient";

/**
 * The AlertsList model module.
 * @module model/AlertsList
 * @version 1.0.0
 */
export class AlertsList {
  /**
   * Constructs a new <code>AlertsList</code>.
   * @alias module:model/AlertsList
   * @class
   * @param searchTerm {String}
   * @param email {String}
   */
  constructor(searchTerm, email) {
    this.searchTerm = searchTerm;
    this.email = email;
  }

  /**
   * Constructs a <code>AlertsList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AlertsList} obj Optional instance to populate.
   * @return {module:model/AlertsList} The populated <code>AlertsList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AlertsList();
      if (data.hasOwnProperty("uuid"))
        obj.uuid = ApiClient.convertToType(data["uuid"], "String");
      if (data.hasOwnProperty("search_term"))
        obj.searchTerm = ApiClient.convertToType(data["search_term"], "String");
      if (data.hasOwnProperty("interval_time"))
        obj.intervalTime = ApiClient.convertToType(
          data["interval_time"],
          "String"
        );
      if (data.hasOwnProperty("email"))
        obj.email = ApiClient.convertToType(data["email"], "String");
    }
    return obj;
  }
}

/**
 * @member {String} uuid
 */
AlertsList.prototype.uuid = undefined;

/**
 * @member {String} searchTerm
 */
AlertsList.prototype.searchTerm = undefined;

/**
 * Allowed values for the <code>intervalTime</code> property.
 * @enum {String}
 * @readonly
 */
AlertsList.IntervalTimeEnum = {
  /**
   * value: "2"
   * @const
   */
  _2: "2",

  /**
   * value: "10"
   * @const
   */
  _10: "10",

  /**
   * value: "30"
   * @const
   */
  _30: "30"
};

/**
 * @member {module:model/AlertsList.IntervalTimeEnum} intervalTime
 */
AlertsList.prototype.intervalTime = undefined;

/**
 * @member {String} email
 */
AlertsList.prototype.email = undefined;
